import argparse
import json
import re
import shutil
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from extract_event_media import bnk_entries, pck_entries


WEM_PATTERN = re.compile(r"\bwem/(\d+)\.wem\b")
GROUP_PATTERN = re.compile(r"^\s*group\s*=\s*-(R|L|S)(\d+)(?:>(\d+))?")
VOLUME_PATTERN = re.compile(r"#v\s+(-?[0-9]+(?:\.[0-9]+)?)dB")
DELAY_PATTERN = re.compile(r"#p\s+([0-9]+(?:\.[0-9]+)?)")


def source_events(project_root):
    whitelist = json.loads((project_root / "mapping" / "old_vehicle_guns.json").read_text(encoding="utf-8"))
    result = set()
    for effect in whitelist["effects"].values():
        result.add(effect["source_player_event"])
        result.add(effect["source_npc_event"])
    canonical = {}
    for event in result:
        canonical.setdefault(event.lower(), event)
    return [canonical[key] for key in sorted(canonical)]


def matching_txtp(txtp_root, event):
    prefix = event.lower() + " "
    return sorted(path for path in txtp_root.glob("*.txtp") if path.name.lower().startswith(prefix))


def extract_media(source_ids, pck_path, bnk_path, wem_root):
    packed = pck_entries(pck_path)
    embedded = bnk_entries(bnk_path)
    wem_root.mkdir(parents=True, exist_ok=True)
    extracted = 0
    with pck_path.open("rb") as stream:
        for source_id in sorted(source_ids):
            destination = wem_root / (str(source_id) + ".wem")
            if source_id in packed:
                entry = packed[source_id]
                stream.seek(entry["offset"])
                destination.write_bytes(stream.read(entry["size"]))
                extracted += 1
            elif source_id in embedded:
                destination.write_bytes(embedded[source_id]["data"])
                extracted += 1
    missing = sorted(source_ids - set(packed) - set(embedded))
    return extracted, missing


def modifiers(line):
    volume_match = VOLUME_PATTERN.search(line)
    delay_match = DELAY_PATTERN.search(line)
    result = {}
    if volume_match is not None:
        result["volume"] = float(volume_match.group(1))
    if delay_match is not None:
        result["delay"] = float(delay_match.group(1))
    return result


def simplify(node):
    if node["kind"] == "silent":
        return None
    if node["kind"] == "sound":
        return node
    children = [value for value in (simplify(child) for child in node["children"]) if value is not None]
    if not children:
        return None
    node["children"] = children
    return node


def parse_txtp(path):
    stack = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        if raw_line.startswith("# AUTOGENERATED"):
            break
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        group_match = GROUP_PATTERN.match(line)
        if group_match is not None:
            count = int(group_match.group(2))
            if count > len(stack):
                raise RuntimeError("Invalid group in {}: {}".format(path, raw_line))
            children = stack[-count:]
            del stack[-count:]
            node = {"kind": "random" if group_match.group(1) == "R" else "layer", "children": children}
            node.update(modifiers(line))
            stack.append(node)
            continue
        wem_match = WEM_PATTERN.search(line)
        if wem_match is not None:
            node = {"kind": "silent"} if line.startswith("?") else {"kind": "sound", "wem": int(wem_match.group(1))}
            node.update(modifiers(line))
            stack.append(node)
            continue
        if line.startswith("?.plugin-"):
            stack.append({"kind": "silent"})
            continue
        raise RuntimeError("Unsupported TXTP line in {}: {}".format(path, raw_line))
    if not stack:
        raise RuntimeError("Empty TXTP graph: {}".format(path))
    root = stack[0] if len(stack) == 1 else {"kind": "layer", "children": stack}
    root = simplify(root)
    if root is None:
        raise RuntimeError("Silent TXTP graph: {}".format(path))
    return root


def count_nodes(node, counts, source_ids):
    counts[node["kind"]] = counts.get(node["kind"], 0) + 1
    if node["kind"] == "sound":
        source_ids.add(node["wem"])
    for child in node.get("children", []):
        count_nodes(child, counts, source_ids)


def decode_one(vgmstream, wem_path, wav_path):
    process = subprocess.run([str(vgmstream), "-i", "-o", str(wav_path), str(wem_path)], capture_output=True, text=True)
    if process.returncode != 0:
        raise RuntimeError("Failed to decode {}: {}".format(wem_path, process.stderr.strip()))


def decode_media(vgmstream, source_ids, wem_root, wav_root, jobs):
    wav_root.mkdir(parents=True, exist_ok=True)
    futures = []
    with ThreadPoolExecutor(max_workers=jobs) as executor:
        for source_id in sorted(source_ids):
            futures.append(executor.submit(decode_one, vgmstream, wem_root / (str(source_id) + ".wem"), wav_root / (str(source_id) + ".wav")))
        for future in as_completed(futures):
            future.result()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--jobs", type=int, default=8)
    args = parser.parse_args()
    project_root = Path(__file__).resolve().parents[1]
    txtp_root = project_root / "work" / "txtp" / "old_all"
    events = source_events(project_root)
    event_paths = {event: matching_txtp(txtp_root, event) for event in events}
    missing_events = [event for event, paths in event_paths.items() if not paths]
    if missing_events:
        raise RuntimeError("Missing TXTP events: " + ", ".join(missing_events))
    output_root = project_root / "work" / "old_event_dynamic"
    if output_root.exists():
        shutil.rmtree(output_root)
    records = []
    source_ids = set()
    counts = {}
    branch_count = 0
    for event in events:
        branches = []
        for index, txtp_path in enumerate(event_paths[event], 1):
            root = parse_txtp(txtp_path)
            count_nodes(root, counts, source_ids)
            branches.append({"branch": index, "txtp": str(txtp_path), "root": root})
            branch_count += 1
        records.append({"event": "oldshoot_" + event.lower(), "source_event": event, "branches": branches})
    wem_root = txtp_root / "wem"
    extracted, missing = extract_media(source_ids, project_root / "work" / "banks" / "old" / "wpn.pck", project_root / "work" / "banks" / "old" / "wpn.bnk", wem_root)
    if missing:
        raise RuntimeError("Missing WEM sources: " + ", ".join(str(value) for value in missing))
    wav_root = output_root / "wav"
    decode_media(project_root / "tools" / "vendor" / "vgmstream" / "vgmstream-cli.exe", source_ids, wem_root, wav_root, max(1, args.jobs))
    manifest = {
        "format": "dynamic-full-v1",
        "events": records,
        "event_count": len(records),
        "txtp_branches": branch_count,
        "wem_sources": len(source_ids),
        "wem_extracted": extracted,
        "wav_root": str(wav_root),
        "media_items": len(source_ids),
        "nodes": counts,
    }
    output_root.mkdir(parents=True, exist_ok=True)
    (output_root / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print("Events: {}".format(len(records)))
    print("TXTP branches: {}".format(branch_count))
    print("WEM sources: {}".format(len(source_ids)))
    print("Nodes: {}".format(counts))


if __name__ == "__main__":
    main()
